make profile card
CEOS-Developers/react-profile pull request #4
Opened 2019-09-27 09:30 UTC by ybh1760

커밋을 자주 했어야 했는데 깜빡하고 한번만 했습니다.

2019-09-27 14:55 UTC, greatSumini reviewed
고생하셨습니다! 스터디때 뵙겠습니다~

2019-09-27 14:55 UTC, orange-mush commented on src/components/Card.js
> +class Card extends Component {
이 Component의 역할을 더 명확히 알 수 있는 이름이라면 좋을 것 같아요! (ex: ProfileCard)

2019-09-27 14:55 UTC, orange-mush commented on src/components/Card.js
> +            {animalList}
ul 태그가 빠졌네요! 절대 빠뜨리시면 안 됩니다. [참고할만한 글](https://stackoverflow.com/questions/2031725/is-using-li-without-enclosing-ul-tags-dangerous)

2019-09-27 14:55 UTC, orange-mush commented on src/App.js
> +        {name:"김서영" ,desc:["안녕하세요 저는 이화여자대학교의 사이버보안학과를 다니고 있습니다." ,"올해는 22살인데 내년엔 23이에요." ,"지금 기분은 불행해요!"]}
1. 정보들이 중복되고 있어요~(ex: 안녕하세요 저는~~의 ~~를 다니고 있습니다) 이런 중복된 코드는 유지보수 시에 아주 큰 장애요소가 된답니다. 예를 들어, 안녕하세요를 하이에블바디로 바꾸고 싶다면 3개의 정보를 모두 바꿔야겠죠?!
2. App Component에서 state로 모든 card의 정보를 저장하고 있을 필요가 있을까요??

2019-09-27 14:55 UTC, orange-mush commented on src/App.js
> +        {animalList:["웜", "트로이목마"]}
animalList라는 property name이 중복돼서 나타나네요 😢

2019-09-27 14:55 UTC, orange-mush commented on src/App.js
> +    let i=0;
index counter로 i, j, k를 쓰는 것은 좋은 습관이 아닙니다! 변수의 역할이 드러나도록 명확한 네이밍을 해주세요 :)

2019-09-27 14:55 UTC, orange-mush commented on src/App.js
> +    while(i<data.length){
배열내의 모든 요소들에 접근할 때 자바스크립트 내장 메서드 map, reduce를 사용하시면 좀 더 직관적인 코드를 짤 수 있어요! [참고할만한 글](https://www.zerocho.com/category/JavaScript/post/5acafb05f24445001b8d796d)

2019-10-02 06:15 UTC, orange-mush commented on src/App.js
> +        <ProfileList />
ProfileList Component를 새로 정의한 점 정말 좋네요!

2019-10-02 06:15 UTC, orange-mush commented on src/components/ProfileCard.js
> +          <ul>{this.getAnimalList()}</ul>
오 함수를 따로 작성해주셨네요! 이건 안 알려줬는데 ㅋㅋㅋㅋㅋ 짱굿입니다

2019-10-02 06:15 UTC, orange-mush commented on src/components/ProfileCard.js
> +    while (i < this.props.profile.animalList.length) {
while문 대신 for문이나 map 함수를 쓰면 더 좋을 것 같아요

2019-10-02 06:15 UTC, orange-mush commented on src/components/ProfileList.js
> +    const profileList = this.state.profiles.map(value => {
위에서는 while문을 썼는데 여기서는 map을 쓰셨네요...?

2019-10-02 06:18 UTC, ybh1760 commented on src/components/ProfileCard.js
> +    while (i < this.props.profile.animalList.length) {
아하 맵으로 바꿔 보겠습니다.

2019-10-02 06:19 UTC, orange-mush commented on src/components/ProfileCard.js
> +  getAnimalList() {
arrow function을 사용해보시는건 어떨까요? 더 안정적인 최신 문법입니다! [참고할만한 글](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/%EC%95%A0%EB%A1%9C%EC%9A%B0_%ED%8E%91%EC%85%98)

2019-10-02 06:24 UTC, hanqyu commented
지나가다가 말씀드리면 커밋할 때 파일이나 코드 단위로 커밋할 수 있기 때문에 커밋 단위를 생각하지 않고 코딩하셔도 돼용. 다만 커밋을 자주하는 습관을 들이시면 커밋하기가 더 좋습니다.

2019-10-02 06:34 UTC, greatSumini requested changes

2019-10-02 06:34 UTC, orange-mush commented on src/components/ProfileCard.js
> +    const animalList = this.props.profile.animalList.map(value => {
animalList를 그대로 return해도 될 것 같아요!

2019-10-02 06:36 UTC, orange-mush commented on src/components/ProfileCard.js
> +    const animalList = this.props.profile.animalList.map(value => {
```suggestion
    return animalList =  this.props.profile.animalList.map(value => {
```
또는
```suggestion
    return this.props.profile.animalList.map(value => {
```
이런식으로용

2019-10-02 06:56 UTC, ybh1760 commented on src/components/ProfileCard.js
> +    const animalList = this.props.profile.animalList.map(value => {
좋은 지적 감사합니다.

2019-10-02 07:18 UTC, merged

2019-10-02 07:21 UTC, orange-mush commented on src/components/ProfileCard.js
> +        <div className="profileCard">
다시 보다가 발견했네요.. 지금 이 div는 아무 의미가 없어도 삭제해도 될 것 같아요